apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.fullname" . }}
  namespace: database
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "mysql.selectorLabels" . | nindent 4 }}
  ports:
    - port: 3306
      targetPort: 3306
      name: mysql