replicaCount: 1

image:
  repository: 842746302447.dkr.ecr.ap-south-1.amazonaws.com/three-tier-poc-backend
  tag: test
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 4000   # update once confirmed from index.js

db:
  host: mysql.database.svc.cluster.local
  port: 3306
  name: transactions

resources:
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

autoscaling:
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80